export const cheese = [
  {'name': 'Frischkäse'},
  {'name': 'Ziegenfrischkäse'},
  {'name': 'Schafsfrischkäse'},
  {'name': 'Hüttenkäse'},
  {'name': 'Schmelzkäse'},
  {'name': 'Roquefort-Käse'},
  {'name': 'Mozzarella'},
  {'name': 'Appenzeller'},
  {'name': 'Emmentaler'},
  {'name': 'Greyerzer'},
  {'name': 'Cheddarkäse'},
  {'name': 'Raclette-Käse'},
  {'name': 'Edamer'},
  {'name': 'Gouda'},
  {'name': 'Tilsiter'},
  {'name': 'Butterkäse'},
  {'name': 'Edelpilzkäse'},
  {'name': 'Havarti-Käse'},
  {'name': 'Brie'},
  {'name': 'Camembert'},
  {'name': 'Limburger Käse'},
  {'name': 'Münsterkäse'},
  {'name': 'Romandour'},
  {'name': 'Bavaria Blu'},
  {'name': 'Bel Paese'},
  {'name': 'Feta'},
  {'name': 'Parmesan'}
]
