export const daries = [
  {'name': 'Skyr'},
  {'name': 'Grana Padano'},
  {'name': 'Parmesan'},
  {'name': 'Ricotta'},
  {'name': 'Mascarpone'},
  {'name': 'Mozzarella'},
  {'name': 'Käse'},
  {'name': 'Remoulade'},
  {'name': 'Schwedenmilch'},
  {'name': 'Ziegenkäse'},
  {'name': 'Schmand'},
  {'name': 'Schafskäse'},
  {'name': 'Pecorino'},
  {'name': 'Molke'},
  {'name': 'Dickmilch'},
  {'name': 'Kefir'},
  {'name': 'Crème fraîche'},
  {'name': 'Crème double'},
  {'name': 'Raclettekäse'},
  {'name': 'Stutenmilch'},
  {'name': 'Schmelzkäse'},
  {'name': 'Weichkäse'},
  {'name': 'Schnittkäse'},
  {'name': 'Schlagsahne'},
  {'name': 'Quark'},
  {'name': 'Buttermilch'},
  {'name': 'Joghurt'},
  {'name': 'Milch'}
]
