export const salat = [
  {'name': 'Zupfsalat'},
  {'name': 'Pflücksalat'},
  {'name': 'Schnittsalat'},
  {'name': 'Eisbergsalat'},
  {'name': 'Radicchio'},
  {'name': 'Ediviensalat'},
  {'name': 'Kopfsalat'},
  {'name': 'Grüner Salat'},
  {'name': 'Feldsalat'},
  {'name': 'Spinat'},
  {'name': 'Chicoree'},
  {'name': 'Mangold'},
  {'name': 'Fenchel'},
  {'name': 'Rauke'},
  {'name': 'Gartenrauke'},
  {'name': 'Artischocke'},
  {'name': 'Bärlauch'},
  {'name': 'Chinakohl'}
]
